name: CI/CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.BETA_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.BETA_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.BETA_AWS_REGION }}

      # Paso 1: Linting
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

      # Paso 2: Build (Skipping tests)
      - name: Build Application
        run: npm run build
        env:
          NODE_ENV: production

      # Paso 3: Empaquetado y subida a S3
      - name: Build and package application
        run: |
          # Your build commands here
          # Package your application into a ZIP file
          zip -r app.zip ./*

      - name: Upload to S3
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          aws s3 cp deployment.zip s3://tu-bucket-s3/deployments/app-$TIMESTAMP.zip

      # Paso 4: Trigger CodeDeploy
      # - name: Trigger CodeDeploy Deployment
      #   run: |
      #     DEPLOYMENT_ID=$(aws deploy create-deployment \
      #       --application-name TuCodeDeployApplication \
      #       --deployment-group-name TuCodeDeployDeploymentGroup \
      #       --s3-location bucket=tu-bucket-s3,key=deployments/app-$TIMESTAMP.zip,bundleType=zip \
      #       --query deploymentId \
      #       --output text)

      #     echo "Deployment ID: $DEPLOYMENT_ID"
